springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

spring:
  application:
    name: financial-monitoring

  datasource:
    url: jdbc:postgresql://localhost:54320/fin_monitoring
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

jwt:
  secret: Fh8eQ2vPp6uKx7MvR0yIzjQ1WxmYzAbC3dEfGhIjKlM=
  expiration-ms: 3600000
